repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml

  - repo: local
    hooks:
      - id: fmt
        name: fmt
        entry: zig fmt --ast-check
        language: system
        types: [ file ]
        files: '\.zig$'
