name: Continuous Integration
on:
  push:
    branches:
      - main
    paths:
      - "**/_test.zig"
  pull_request:
jobs:
  run_tests_and_upload_codecov:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mlugg/setup-zig@v1
        with:
          version: 0.13.0
      - run: |
          brew install kcov
          sudo zig build coverage
      - name: upload codecov
        uses: codecov/codecov-action@v5
        with:
          directory: coverage
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          verbose: true
